"""Compatibility exports for terminal dashboard panels."""

from memo.tui.dashboard.panels import (
    _daemon_status,
    _dir_size,
    _fetch_memflow_utility,
    _get_corpus_rows,
    _grounding_citation_stats,
    _human_age,
    _human_bytes,
    _memflow_bin,
    _panel_activity,
    _panel_consumers,
    _panel_corpus,
    _panel_memflow,
    _panel_recall_quality,
    _panel_recall_trend,
    _panel_recent_recalls,
    _panel_recent_saves,
    _panel_runtime,
    _panel_top_tags,
    _panel_utility,
    _panel_verdict,
    _read_eval_history,
    _TTLCache,
    _watcher_status,
    sparkline,
)

__all__ = [
    "_TTLCache",
    "_daemon_status",
    "_dir_size",
    "_fetch_memflow_utility",
    "_get_corpus_rows",
    "_grounding_citation_stats",
    "_human_age",
    "_human_bytes",
    "_memflow_bin",
    "_panel_activity",
    "_panel_consumers",
    "_panel_corpus",
    "_panel_memflow",
    "_panel_recall_quality",
    "_panel_recall_trend",
    "_panel_recent_recalls",
    "_panel_recent_saves",
    "_panel_runtime",
    "_panel_top_tags",
    "_panel_utility",
    "_panel_verdict",
    "_read_eval_history",
    "_watcher_status",
    "sparkline",
]
