"""Curated knowledge-graph projection and retrieval flags."""

from __future__ import annotations

from memo.flags_base import FlagSpec, _spec

SPECS: tuple[FlagSpec, ...] = (
    _spec(
        "MEMO_GRAPH_PROJECTION_ENABLED",
        "bool",
        False,
        "graph",
        "Serve retrieval graph reads from the active curated projection.",
    ),
    _spec(
        "MEMO_GRAPH_PROJECTION_MIN_QUALITY",
        "float",
        0.45,
        "graph",
        "Minimum deterministic node quality admitted to the serving projection.",
        min_val=0.0,
        max_val=1.0,
    ),
    _spec(
        "MEMO_GRAPH_PROJECTION_MAX_AGE_HOURS",
        "int",
        36,
        "graph",
        "Maximum active projection age before graph serving fails open.",
        min_val=1,
    ),
    _spec(
        "MEMO_GRAPH_SIGNAL_ENABLED",
        "bool",
        False,
        "graph",
        "Reorder eligible retrieval hits with the curated graph signal.",
    ),
    _spec(
        "MEMO_GRAPH_REASON_ENABLED",
        "bool",
        False,
        "graph",
        "Attach structured graph evidence to graph-touched hits.",
    ),
    _spec(
        "MEMO_GRAPH_SEMANTIC_RELATIONS",
        "bool",
        False,
        "graph",
        "Include stored semantic relations in graph explanations.",
    ),
    _spec(
        "MEMO_GRAPH_HUB_SUPPRESSION",
        "bool",
        True,
        "graph",
        "Prevent non-explicit high-document-frequency hubs from affecting ranking.",
    ),
    _spec(
        "MEMO_GRAPH_HUB_MAX_DOC_FREQ_RATIO",
        "float",
        0.25,
        "graph",
        "Document-frequency ratio that marks a projected entity as a hub.",
        min_val=0.0,
        max_val=1.0,
    ),
    _spec(
        "MEMO_GRAPH_MIN_ENTITY_IDF",
        "float",
        0.5,
        "graph",
        "Minimum query-entity IDF allowed to contribute graph signal.",
        min_val=0.0,
    ),
    _spec(
        "MEMO_GRAPH_SIGNAL_BUDGET_MS",
        "int",
        150,
        "graph",
        "Hard graph-signal deadline in milliseconds.",
        min_val=0,
    ),
    _spec(
        "MEMO_GRAPH_SIGNAL_ALPHA",
        "float",
        0.15,
        "graph",
        "Curated graph rank weight in weighted reciprocal-rank fusion.",
        min_val=0.0,
        max_val=0.5,
    ),
    _spec(
        "MEMO_GRAPH_CODE_TRACE_ENABLED",
        "bool",
        False,
        "graph",
        "Project captured memory-to-codegraph evidence with stable code URIs.",
    ),
    _spec(
        "MEMO_GRAPH_DISCOVERY_ENABLED",
        "bool",
        False,
        "graph",
        "Expose bounded community and bridge discovery over the curated projection.",
    ),
    _spec(
        "MEMO_GRAPH_OUTCOME_SIGNAL_ENABLED",
        "bool",
        False,
        "graph",
        "Deprecated outcome modulation switch retained for config compatibility.",
    ),
    _spec(
        "MEMO_GRAPH_OUTCOME_WEIGHT",
        "float",
        0.05,
        "graph",
        "Deprecated outcome modulation weight retained for config compatibility.",
        min_val=0.0,
    ),
    _spec(
        "MEMO_GRAPH_RETRIEVAL_ENABLED",
        "bool",
        False,
        "graph",
        "Deprecated compatibility switch; graph-only candidate injection is not served.",
    ),
    _spec(
        "MEMO_GRAPH_FALLBACK_MIN_HITS",
        "int",
        0,
        "graph",
        "Deprecated compatibility value; graph-only fallback is not served.",
        min_val=0,
    ),
    _spec(
        "MEMO_GRAPH_DENSITY_BOOST",
        "float",
        0.0,
        "graph",
        "Deprecated compatibility value; density score mutation is not served.",
        min_val=0.0,
    ),
    _spec(
        "MEMO_GRAPH_EXPANSION_ENABLED",
        "bool",
        False,
        "graph",
        "Deprecated compatibility switch; graph-only expansion is not served.",
    ),
    _spec(
        "MEMO_EVIDENCE_GRAPH_COMPACT",
        "bool",
        True,
        "graph",
        "Collapse memo_evidence_pack hits sharing a rare entity into one "
        "representative before packing (citing absorbed hits by id). Graduated "
        "2026-08-04 after ad-hoc validation against the live index showed no "
        "coverage regression (see memo decision 2830cb72).",
    ),
    _spec(
        "MEMO_EVIDENCE_GRAPH_COMPACT_MIN_IDF",
        "float",
        0.5,
        "graph",
        "Minimum IDF-weighted entity overlap required to collapse two "
        "evidence_pack hits into one representative.",
        min_val=0.0,
    ),
)
