from __future__ import annotations

import re
import sys
from pathlib import Path

import click

from memo.cli_common import console

_WRAPPER_SNIPPET_ZSH = r"""# >>> memo session-resume wrapper >>>
# Auto-suggest resuming recent Claude Code sessions for the current cwd.
# Generated by `memo install-shell-wrapper`. Do not edit by hand — re-run
# the install command instead. To remove: delete this file and the
# matching `source` line in your shell rc.
#
# If you previously had `alias claude='claude --flag1 --flag2'`, migrate
# to:   MEMO_CLAUDE_EXTRA_ARGS=(--flag1 --flag2)
# Those flags are forwarded to every `command claude` invocation.

# ISO-8601 → relative string (macOS date -j).
_memo_reltime() {
    local iso="${1:0:19}" then now diff
    then=$(date -j -f "%Y-%m-%dT%H:%M:%S" "$iso" "+%s" 2>/dev/null) || { echo "?"; return; }
    now=$(date +%s); diff=$(( now - then ))
    (( diff < 60    )) && { echo "now"; return; }
    (( diff < 3600  )) && { printf "%dm ago" $(( diff/60   )); return; }
    (( diff < 86400 )) && { printf "%dh ago" $(( diff/3600 )); return; }
                           printf "%dd ago"  $(( diff/86400 ))
}

# One │ padded-content │ row. Reads _CW, C, R from caller scope (dynamic).
_memo_bl() {
    local padded
    padded=$(printf "%-${_CW}s" "${1:0:${_CW}}")
    printf "  ${C}│${R} ${2:-}${padded}${R} ${C}│${R}\n"
}

function claude() {
    local extra_args=("${MEMO_CLAUDE_EXTRA_ARGS[@]}")

    # Pass-through: args present, stdin not a TTY, or required tools missing.
    (( $# > 0 ))  && { command claude "${extra_args[@]}" "$@"; return; }
    [[ ! -t 0 ]] && { command claude "${extra_args[@]}"; return; }
    { command -v memo && command -v jq; } >/dev/null 2>&1 \
        || { command claude "${extra_args[@]}"; return; }

    local raw count
    raw=$(memo resume --json --limit 5 --cwd "$PWD" 2>/dev/null) || raw=""
    count=$(printf '%s' "$raw" | jq 'length' 2>/dev/null)
    [[ -z "$count" || "$count" == "0" ]] && { command claude "${extra_args[@]}"; return; }

    # ANSI colors — suppressed on dumb terminals.
    local R='' B='' D='' C='' G='' GR='' W=''
    [[ -t 1 && "${TERM:-dumb}" != "dumb" ]] && {
        R=$'\e[0m' B=$'\e[1m' D=$'\e[2m'
        C=$'\e[96m' G=$'\e[92m' GR=$'\e[90m' W=$'\e[97m'
    }

    # Box: 60 chars of content, 62-char horizontal rule.
    local _CW=60
    local _HL; _HL=$(printf '%0.s─' {1..62})

    printf "\n  ${C}╭${_HL}╮${R}\n"

    if [[ "$count" == "1" ]]; then
        local sid project branch turns when summary
        sid=$(     printf '%s' "$raw" | jq -r '.[0].session_id')
        project=$( printf '%s' "$raw" | jq -r '.[0].project    // "?"')
        branch=$(  printf '%s' "$raw" | jq -r '.[0].branch     // "?"')
        turns=$(   printf '%s' "$raw" | jq -r '.[0].turn_count // 0')
        when=$(    _memo_reltime "$(printf '%s' "$raw" | jq -r '.[0].updated')")
        summary=$( printf '%s' "$raw" | jq -r '.[0].summary // .[0].last_user_msg // "—"')

        _memo_bl ""
        _memo_bl "  ${project}  ·  ${branch}  ·  ${when}  ·  ${turns} turns" "${D}"
        _memo_bl "  ${summary}" "${B}${W}"
        _memo_bl ""
        printf "  ${C}╰${_HL}╯${R}\n"

        printf "\n  ${G}${B}Continue?${R}  ${B}Y${R}${G} resume  ${GR}n new session${R}  "
        local ans; read -rk1 ans; printf "\n\n"

        if [[ "$ans" == [yY] || "$ans" == $'\n' || "$ans" == $'\r' || -z "$ans" ]]; then
            command claude --resume "$sid" "${extra_args[@]}"
        else
            command claude "${extra_args[@]}"
        fi

    else
        local sw=$(( _CW - 2 - 1 - 8 - 1 - 12 - 1 ))  # 35 chars for summary
        _memo_bl "  ${count} previous sessions — pick which to resume" "${D}"
        _memo_bl ""

        local i idx r_branch r_when r_summary pn pw pb ps
        for (( i=1; i<=count; i++ )); do
            idx=$(( i - 1 ))
            r_branch=$( printf '%s' "$raw" | jq -r ".[$idx].branch // \"—\"")
            r_when=$(   _memo_reltime "$(printf '%s' "$raw" | jq -r ".[$idx].updated")")
            r_summary=$(printf '%s' "$raw" | jq -r ".[$idx].summary // .[$idx].last_user_msg // \"—\"")

            pn=$(printf "%-2s"      "$i")
            pw=$(printf "%-8s"      "${r_when}")
            pb=$(printf "%-12s"     "${r_branch:0:12}")
            ps=$(printf "%-${sw}s"  "${r_summary:0:${sw}}")

            printf "  ${C}│${R} ${B}${pn}${R} ${D}${pw}${R} ${pb} ${W}${ps}${R} ${C}│${R}\n"
        done

        _memo_bl ""
        _memo_bl "  n  new session" "${GR}"
        _memo_bl ""
        printf "  ${C}╰${_HL}╯${R}\n"

        printf "\n  ${G}${B}Choose${R}  ${GR}[1-${count}] resume  n new${R}  "
        local choice; read choice; printf "\n"

        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= count )); then
            local sid
            sid=$(printf '%s' "$raw" | jq -r ".[$(( choice - 1 ))].session_id")
            command claude --resume "$sid" "${extra_args[@]}"
        else
            command claude "${extra_args[@]}"
        fi
    fi
}
# <<< memo session-resume wrapper <<<
"""


@click.command(name="install-shell-wrapper")
@click.option("--print", "do_print", is_flag=True, help="Print the wrapper snippet to stdout. Default mode when neither --print nor --write is set.")
@click.option("--write", "do_write", is_flag=True, help="Write ~/.zsh/memo-wrapper.zsh and append the matching `source` line to ~/.zshrc (idempotent).")
@click.option("--shell", "shell_kind", type=click.Choice(["zsh"]), default="zsh", show_default=True, help="Target shell. Only zsh is supported (the wrapper uses zsh-specific builtins).")
@click.option("--force", is_flag=True, help="Overwrite ~/.zsh/memo-wrapper.zsh even if its content differs from what we would write.")
def install_shell_wrapper(do_print: bool, do_write: bool, shell_kind: str, force: bool) -> None:
    snippet = _WRAPPER_SNIPPET_ZSH
    if not do_write:
        click.echo(snippet)
        if not do_print:
            click.echo(
                "\n(pass `--write` to install into ~/.zsh/memo-wrapper.zsh + ~/.zshrc.)",
                err=True,
            )
        return

    home = Path.home()
    wrapper_dir = home / ".zsh"
    wrapper_path = wrapper_dir / "memo-wrapper.zsh"
    rc_path = home / (".zshrc" if shell_kind == "zsh" else ".bashrc")
    source_line = f"[[ -f {wrapper_path} ]] && source {wrapper_path}"

    wrapper_dir.mkdir(parents=True, exist_ok=True)
    if wrapper_path.is_file():
        existing = wrapper_path.read_text(encoding="utf-8")
        if existing == snippet:
            console.print(f"[dim]✓ {wrapper_path} already up to date[/dim]")
        elif not force:
            console.print(
                f"[red]✗[/red] {wrapper_path} exists with different content. "
                f"Pass [bold]--force[/bold] to overwrite.",
            )
            sys.exit(2)
        else:
            wrapper_path.write_text(snippet, encoding="utf-8")
            console.print(f"[yellow]↻[/yellow] {wrapper_path} overwritten (--force)")
    else:
        wrapper_path.write_text(snippet, encoding="utf-8")
        console.print(f"[green]✓[/green] {wrapper_path} created")

    rc_existing = rc_path.read_text(encoding="utf-8") if rc_path.is_file() else ""
    if source_line in rc_existing:
        console.print(f"[dim]✓ {rc_path} already has the source line[/dim]")
    else:
        with rc_path.open("a", encoding="utf-8") as fh:
            if rc_existing and not rc_existing.endswith("\n"):
                fh.write("\n")
            fh.write("\n# memo session-resume wrapper\n")
            fh.write(f"{source_line}\n")
        console.print(f"[green]✓[/green] {rc_path} ← appended source line")

    try:
        rc_text = rc_path.read_text(encoding="utf-8")
    except OSError:
        rc_text = ""
    alias_match = re.search(r"^\s*alias\s+claude\s*=.*$", rc_text, re.MULTILINE)
    if alias_match:
        console.print(
            f"[yellow]heads-up:[/yellow] found a pre-existing `{alias_match.group(0).strip()}` "
            f"in {rc_path}.\n"
            f"  The wrapper function will shadow it. To preserve those flags,\n"
            f"  remove the alias and use [bold]MEMO_CLAUDE_EXTRA_ARGS[/bold]:\n"
            f"    [dim]export MEMO_CLAUDE_EXTRA_ARGS=(--your-flag --other-flag)[/dim]",
        )
